# Generated by Django 4.2.4 on 2023-10-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
